imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    uri.uploads: /uploads/
    uri.uploads.cache: /uploads/cache/
    directorio.uploads: %kernel.root_dir%/../web/uploads/
    directorio.uploads.cache: %kernel.root_dir%/../web/uploads/cache/


framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
    
sensio_framework_extra:
    view:
        annotations: false

fos_rest:
    view:
        #view_response_listener: false
        view_response_listener: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: php
        formats:
            json: true
    routing_loader:
        default_format: json        
    body_listener:
        decoders:
            json: fos_rest.decoder.json
            xml: fos_rest.decoder.xml  
    allowed_methods_listener: true                  
    service:
        router: router
        templating: templating
        serializer: serializer
        view_handler: fos_rest.view_handler.default     