<?php

namespace MiCiudad\ModeloBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CampoExtendidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampoExtendidoRepository extends EntityRepository
{
}
