<?php

namespace MiCiudad\ModeloBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DatoExtendidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatoExtendidoRepository extends EntityRepository
{
}
