<?php

namespace MiCiudad\ModeloBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SolicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudRepository extends EntityRepository
{
}
