<?php

namespace MiCiudad\ModeloBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TipoControlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoControlRepository extends EntityRepository
{
}
