<?php

namespace MiCiudad\ModeloBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TipoSolicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoSolicitudRepository extends EntityRepository
{
}
